title: Pooya Jamshidi
logo: http://pooya-jamshidi.github.io/Me.jpg
description: "pooya.jamshidi[At]ut.ac.ir <br> jamshidii.pooya[At]gmail.com <br><br> N. Kargar Ave., Tehran, Iran."
theme: jekyll-theme-minimal
google_analytics:

