title: Pooya Jamshidi
logo: http://pooya-jamshidi.github.io/Me.jpg
description: "pooya.jamshidi [At] ut [dot] ac [dot] ir <br> jamshidii.pooya [At] gmail [dot] com <br><br> N. Kargar Ave., Tehran, Iran."
theme: jekyll-theme-minimal
google_analytics:

